name: ai_first_project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stop_watch_timer: ^0.4.0
  tuple: ^1.0.3
  provider: ^4.3.1
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/Raleway-Italic-VariableFont_wght.ttf
        - asset: fonts/Raleway/Raleway-VariableFont_wght.ttf
          
    - family: Lato
      fonts:
        - asset: fonts\Lato\Lato-Black.ttf
        - asset: fonts\Lato\Lato-BlackItalic.ttf
        - asset: fonts\Lato\Lato-Bold.ttf
        - asset: fonts\Lato\Lato-BoldItalic.ttf
        - asset: fonts\Lato\Lato-Italic.ttf
        - asset: fonts\Lato\Lato-Light.ttf
        - asset: fonts\Lato\Lato-LightItalic.ttf
        - asset: fonts\Lato\Lato-Regular.ttf
        - asset: fonts\Lato\Lato-Thin.ttf
        - asset: fonts\Lato\Lato-ThinItalic.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
